[build]
  command = "npm run build"
  publish = "dist"

[secrets_scan]
  enabled = false

[[redirects]]
  from = "http://yourdomain.com/*"
  to = "https://yourdomain.com/:splat"
  status = 301
  force = true
