[build]
  command = "npm run build"
  publish = "dist"

[secrets_scan]
  enabled = false

[[redirects]]
  from = "http://muhammedrizin.in/*"
  to = "https://muhammedrizin.in/:splat"
  status = 301
  force = true
